// GENERATED by scripts/film-data.mjs from the film's chapters.json — do not edit by hand.

export interface FilmSentence {
  text: string;
  start: number;
}

export interface FilmChapter {
  id: string;
  title: string;
  start: number;
  sentences: FilmSentence[];
}

export const FILM = {
  duration: 0,
  src: '/video/dmc-safety-how-it-works.mp4',
  poster: '/video/poster.jpg',
  captions: '/video/captions.vtt',
  chapters: [] as FilmChapter[],
};
