// GENERATED by scripts/film-data.mjs from the film's chapters.json — do not edit by hand.
import type { FilmData } from './types';

export const FILM: FilmData = {
  duration: 188,
  src: '/video/how-to-join/dmc-safety-how-to-join.mp4',
  poster: '/video/how-to-join/poster.jpg',
  captions: '/video/how-to-join/captions.vtt',
  chapters: [
    {
      "id": "01-who-can-join",
      "title": "Who can join",
      "start": 0,
      "sentences": [
        {
          "text": "This film shows how to join the Downtown safety network, and how to take part.",
          "start": 0.35
        },
        {
          "text": "The safety dashboard connects Downtown businesses and Downtown public-safety officers.",
          "start": 6.55
        },
        {
          "text": "A business registers with only an email.",
          "start": 12.23
        },
        {
          "text": "An officer joins when an administrator sends an invitation.",
          "start": 15.3
        },
        {
          "text": "A business association can get an access code for its members.",
          "start": 19.23
        },
        {
          "text": "Everyone can see the public live map.",
          "start": 23.27
        },
        {
          "text": "No account is necessary.",
          "start": 26.07
        }
      ]
    },
    {
      "id": "02-register-your-business",
      "title": "Register your business",
      "start": 28.8,
      "sentences": [
        {
          "text": "To register a business, open 901safety.com.",
          "start": 29.15
        },
        {
          "text": "Select Register your business.",
          "start": 33.87
        },
        {
          "text": "Type your work email.",
          "start": 36.59
        },
        {
          "text": "Then select Email me a sign-in link.",
          "start": 38.67
        },
        {
          "text": "Your email makes your account.",
          "start": 41.79
        },
        {
          "text": "You do not need a password.",
          "start": 44.15
        },
        {
          "text": "Open the email, and select Sign in.",
          "start": 47.25
        },
        {
          "text": "The link works one time, and it expires after one hour.",
          "start": 50.45
        }
      ]
    },
    {
      "id": "03-join-with-an-access-code",
      "title": "Join with an access code",
      "start": 55.4,
      "sentences": [
        {
          "text": "If you have an access code, open 901safety.com/join.",
          "start": 55.75
        },
        {
          "text": "The code comes from the Downtown safety team, or from your business association.",
          "start": 61.51
        },
        {
          "text": "Type the code and your work email.",
          "start": 66.63
        },
        {
          "text": "Then select Join.",
          "start": 69.11
        },
        {
          "text": "Open the email, and finish joining.",
          "start": 71.11
        }
      ]
    },
    {
      "id": "04-set-up-your-storefront",
      "title": "Set up your storefront",
      "start": 74.4,
      "sentences": [
        {
          "text": "The first time you sign in, set up your storefront.",
          "start": 74.75
        },
        {
          "text": "Select Set up now.",
          "start": 78.35
        },
        {
          "text": "Type the business name and the street address.",
          "start": 80.43
        },
        {
          "text": "The address puts your business on the map.",
          "start": 83.23
        },
        {
          "text": "It also sets which alerts you get, in a half-mile radius.",
          "start": 86.08
        },
        {
          "text": "Then select Register storefront.",
          "start": 90.19
        },
        {
          "text": "To sign in faster next time, select Add passkey.",
          "start": 92.75
        },
        {
          "text": "Then use Face ID, Touch ID or your device PIN.",
          "start": 96.75
        }
      ]
    },
    {
      "id": "05-take-part-every-day",
      "title": "Take part every day",
      "start": 101.8,
      "sentences": [
        {
          "text": "Your home page shows the active alerts in a half-mile radius of your business.",
          "start": 102.15
        },
        {
          "text": "Your block shows the last 48 hours on a map.",
          "start": 107.27
        },
        {
          "text": "To report what you see, select Talk, Form or Quick alert.",
          "start": 110.92
        },
        {
          "text": "My reports shows the status of each report that you send.",
          "start": 115.75
        },
        {
          "text": "To hear new alerts, select Turn on, in Spoken alerts.",
          "start": 119.83
        },
        {
          "text": "Keep the dashboard open in a browser tab to get alerts.",
          "start": 124.15
        }
      ]
    },
    {
      "id": "06-the-lookout-board",
      "title": "The Lookout board",
      "start": 128.3,
      "sentences": [
        {
          "text": "The Lookout board shows people and vehicles that officers ask you to watch for.",
          "start": 128.65
        },
        {
          "text": "Warning: do not approach, follow or stop anyone.",
          "start": 134.29
        },
        {
          "text": "If you see a match, select I've seen this.",
          "start": 138.68
        },
        {
          "text": "Show where you saw them, and add a note.",
          "start": 142.17
        },
        {
          "text": "Then select Send to officers.",
          "start": 144.97
        },
        {
          "text": "Officers get your sighting at once.",
          "start": 147.77
        }
      ]
    },
    {
      "id": "07-for-everyone-downtown",
      "title": "For everyone downtown",
      "start": 151.2,
      "sentences": [
        {
          "text": "Neighbors, property managers and associations can follow the public live map.",
          "start": 151.55
        },
        {
          "text": "No account is necessary.",
          "start": 157.15
        },
        {
          "text": "The map shows the type of each report, its status and an approximate place.",
          "start": 159.31
        },
        {
          "text": "It never shows names, photos or addresses.",
          "start": 164.75
        },
        {
          "text": "A business association can ask the safety team for an access code for its members.",
          "start": 168.67
        }
      ]
    },
    {
      "id": "08-scan-to-join",
      "title": "Scan to join",
      "start": 174.7,
      "sentences": [
        {
          "text": "Join the people who watch out for Downtown.",
          "start": 175.05
        },
        {
          "text": "Scan the code to join.",
          "start": 178.17
        }
      ]
    }
  ],
};
