// GENERATED by scripts/film-data.mjs from the film's chapters.json — do not edit by hand.
import type { FilmData } from './types';

export const FILM: FilmData = {
  duration: 188.5,
  src: '/video/how-to-report/dmc-safety-how-to-report.mp4',
  poster: '/video/how-to-report/poster.jpg',
  captions: '/video/how-to-report/captions.vtt',
  chapters: [
    {
      "id": "01-before-you-report",
      "title": "Before you report",
      "start": 0,
      "sentences": [
        {
          "text": "This film shows how to report an incident, and how officers respond.",
          "start": 0.35
        },
        {
          "text": "Warning.",
          "start": 6.45
        },
        {
          "text": "If a person is in danger, call 911 first.",
          "start": 7.57
        },
        {
          "text": "To make a report, select Report an incident.",
          "start": 11.52
        },
        {
          "text": "Then select a method: Report by voice, Guided form, or Quick alert.",
          "start": 15.09
        }
      ]
    },
    {
      "id": "02-report-by-voice",
      "title": "Report by voice",
      "start": 21.4,
      "sentences": [
        {
          "text": "For a report by voice, select Start talking.",
          "start": 21.75
        },
        {
          "text": "Select Start voice interview.",
          "start": 25.59
        },
        {
          "text": "Then allow the microphone.",
          "start": 27.99
        },
        {
          "text": "The interviewer speaks first.",
          "start": 29.99
        },
        {
          "text": "Hi, you've reached the Downtown safety line.",
          "start": 32.62,
          "speaker": "interviewer"
        },
        {
          "text": "What happened?",
          "start": 35.74,
          "speaker": "interviewer"
        },
        {
          "text": "Hi.",
          "start": 36.99,
          "speaker": "caller"
        },
        {
          "text": "A man is pulling on car door handles on South Second Street, right now.",
          "start": 37.79,
          "speaker": "caller"
        },
        {
          "text": "Is anyone hurt, and did you see a weapon?",
          "start": 42.48,
          "speaker": "interviewer"
        },
        {
          "text": "Answer in your own words.",
          "start": 46.09
        },
        {
          "text": "It asks one short question at a time, and you can interrupt it.",
          "start": 48.41
        },
        {
          "text": "When it has the facts, it fills in the report on your screen.",
          "start": 52.97
        },
        {
          "text": "Then select Review and submit.",
          "start": 57.29
        }
      ]
    },
    {
      "id": "03-the-guided-form",
      "title": "The guided form",
      "start": 60.4,
      "sentences": [
        {
          "text": "The guided form has five short steps.",
          "start": 60.75
        },
        {
          "text": "First, select what is happening.",
          "start": 64.03
        },
        {
          "text": "If it is happening now, set the switch.",
          "start": 66.67
        },
        {
          "text": "Also set a switch if you saw a weapon, or if a person is hurt.",
          "start": 69.63
        },
        {
          "text": "Next, show the place: your business, or a pin on the map.",
          "start": 74.19
        },
        {
          "text": "Then describe each person or vehicle.",
          "start": 79.07
        },
        {
          "text": "In Details, type what happened, or select Dictate and speak.",
          "start": 82.19
        },
        {
          "text": "Organize my notes fills in the fields for you.",
          "start": 87.15
        },
        {
          "text": "Then select Review report.",
          "start": 90.43
        }
      ]
    },
    {
      "id": "04-quick-alert",
      "title": "Quick alert",
      "start": 93.5,
      "sentences": [
        {
          "text": "If there is no time, use a quick alert.",
          "start": 93.85
        },
        {
          "text": "Select what is happening.",
          "start": 97.21
        },
        {
          "text": "Then select Send alert now.",
          "start": 98.89
        },
        {
          "text": "Officers and nearby businesses get the alert at once.",
          "start": 101.85
        }
      ]
    },
    {
      "id": "05-review-send-and-follow-the-status",
      "title": "Review, send, and follow the status",
      "start": 106.4,
      "sentences": [
        {
          "text": "Before you send, check the report.",
          "start": 106.75
        },
        {
          "text": "The dashboard suggests a priority, from P1 to P4.",
          "start": 109.63
        },
        {
          "text": "Alert nearby businesses is on.",
          "start": 114.62
        },
        {
          "text": "For officers only, set it to off.",
          "start": 117.34
        },
        {
          "text": "Officers may contact me lets an officer call you.",
          "start": 120.51
        },
        {
          "text": "Select Send to officers.",
          "start": 124.27
        },
        {
          "text": "You hear the report read back.",
          "start": 126.67
        },
        {
          "text": "In My reports, follow each status, from Received to Resolved.",
          "start": 129.15
        }
      ]
    },
    {
      "id": "06-officers-respond-to-a-report",
      "title": "Officers: respond to a report",
      "start": 135.7,
      "sentences": [
        {
          "text": "Officers see each new report at once, in the Operations Center.",
          "start": 136.05
        },
        {
          "text": "The most urgent reports are at the top.",
          "start": 140.69
        },
        {
          "text": "With Voice alerts on, the dashboard reads new reports aloud.",
          "start": 143.57
        },
        {
          "text": "Select a report to open it.",
          "start": 147.97
        },
        {
          "text": "Select Acknowledge.",
          "start": 150.41
        },
        {
          "text": "The reporter then sees Seen by officers.",
          "start": 152.05
        },
        {
          "text": "When you go to the place, select Responding.",
          "start": 155.6
        },
        {
          "text": "Add a note: internal, or visible to the reporter.",
          "start": 158.77
        },
        {
          "text": "To warn others about a person or a vehicle, select BOLO.",
          "start": 162.88
        },
        {
          "text": "When you finish, select Resolve.",
          "start": 167.2
        },
        {
          "text": "Select an outcome.",
          "start": 169.89
        },
        {
          "text": "Then select Mark resolved.",
          "start": 171.41
        }
      ]
    },
    {
      "id": "07-scan-to-report",
      "title": "Scan to report",
      "start": 174.5,
      "sentences": [
        {
          "text": "Report what you see.",
          "start": 174.85
        },
        {
          "text": "Officers respond.",
          "start": 176.77
        },
        {
          "text": "Scan the code to make a report.",
          "start": 178.69
        }
      ]
    }
  ],
};
