// GENERATED by scripts/film-data.mjs from the film's chapters.json — do not edit by hand.
import type { FilmData } from './types';

export const FILM: FilmData = {
  duration: 30.02,
  src: '/video/in-30-seconds/dmc-safety-in-30-seconds.mp4',
  poster: '/video/in-30-seconds/poster.jpg',
  captions: '/video/in-30-seconds/captions.vtt',
  chapters: [
    {
      "id": "01-report-what-you-see",
      "title": "Report what you see",
      "start": 0,
      "sentences": [
        {
          "text": "See something downtown that does not look right?",
          "start": 0.2
        },
        {
          "text": "Report it on the safety dashboard: by voice, with the guided form, or with a quick alert.",
          "start": 3.4
        }
      ]
    },
    {
      "id": "02-officers-respond",
      "title": "Officers respond",
      "start": 10,
      "sentences": [
        {
          "text": "Officers pick it up and respond, and you get updates.",
          "start": 10.2
        }
      ]
    },
    {
      "id": "03-nearby-alerts-and-the-lookout-board",
      "title": "Nearby alerts and the Lookout board",
      "start": 14.7,
      "sentences": [
        {
          "text": "Businesses nearby get an alert, and the Lookout board shows who to watch for.",
          "start": 14.9
        }
      ]
    },
    {
      "id": "04-the-public-live-map",
      "title": "The public live map",
      "start": 20.4,
      "sentences": [
        {
          "text": "Everyone downtown can follow the public live map.",
          "start": 20.6
        }
      ]
    },
    {
      "id": "05-scan-to-join",
      "title": "Scan to join",
      "start": 24.5,
      "sentences": [
        {
          "text": "Register with only your work email.",
          "start": 24.7
        },
        {
          "text": "Scan the code to join.",
          "start": 27.34
        }
      ]
    }
  ],
};
