#!/usr/bin/env node
/**
 * Bring the "How it works" film into the site.
 *
 *   node scripts/film-data.mjs <film renders dir> [upload date YYYY-MM-DD]
 *
 * Reads <dir>/chapters.json (from the film project's web-assets step), copies
 * the web encode, poster and captions into public/video/, writes
 * src/film/filmData.ts, and fills the video meta + VideoObject JSON-LD between
 * the markers in how-it-works.html. Refuses words the owner ruled out of the
 * product's language.
 */
import { copyFileSync, existsSync, mkdirSync, readFileSync, statSync, writeFileSync } from 'node:fs';
import { join, resolve } from 'node:path';

const ROOT = resolve(import.meta.dirname, '..');
const SITE = 'https://www.901safety.com';
const PAGE = `${SITE}/how-it-works`;
const [dirArg, dateArg] = process.argv.slice(2);
if (!dirArg) {
  console.error('usage: node scripts/film-data.mjs <film renders dir> [YYYY-MM-DD]');
  process.exit(1);
}
const dir = resolve(dirArg);
const uploadDate = dateArg ?? new Date().toISOString().slice(0, 10);

const MEDIA = [
  ['dmc-safety-how-it-works-web.mp4', 'dmc-safety-how-it-works.mp4'],
  ['poster.jpg', 'poster.jpg'],
  ['captions.vtt', 'captions.vtt'],
  // public/video/og-image.png (the share card) is the site's own: scripts/og-images.mjs
];
for (const [from] of MEDIA) {
  if (!existsSync(join(dir, from))) throw new Error(`missing ${join(dir, from)}`);
}

const data = JSON.parse(readFileSync(join(dir, 'chapters.json'), 'utf8'));
const duration = Number(data.duration);
if (!(duration > 0)) throw new Error('chapters.json: duration must be > 0');
const chapters = (data.chapters ?? []).map((c, i) => ({
  id: String(c.id ?? `chapter-${i + 1}`),
  title: String(c.title ?? '').trim(),
  start: Math.round(Number(c.start) * 100) / 100,
  sentences: (c.sentences ?? []).map((s) => ({
    text: String(s.text ?? '').trim(),
    start: Math.round(Number(s.start) * 100) / 100,
  })),
}));
if (!chapters.length) throw new Error('chapters.json: no chapters');
chapters.forEach((c, i) => {
  if (!c.title) throw new Error(`chapter ${i + 1}: no title`);
  if (!(c.start >= 0 && c.start < duration)) throw new Error(`chapter ${i + 1}: start ${c.start} outside 0..${duration}`);
  if (i && c.start <= chapters[i - 1].start) throw new Error(`chapter ${i + 1}: starts before the previous one`);
});

// The owner's rule (2026-10-08): no "AI" in the product's words.
const BANNED = [/\bAI\b/, /artificial intelligence/i, /\bGPT\b/i, /openai/i, /elevenlabs/i, /chat ?bot/i];
const words = chapters.flatMap((c) => [c.title, ...c.sentences.map((s) => s.text)]);
const hits = words.filter((w) => BANNED.some((re) => re.test(w)));
if (hits.length) throw new Error(`banned wording in the film text:\n  ${hits.join('\n  ')}`);

// 1. media → public/video
const out = join(ROOT, 'public', 'video');
mkdirSync(out, { recursive: true });
for (const [from, to] of MEDIA) copyFileSync(join(dir, from), join(out, to));

// 2. src/film/filmData.ts
const ts = `// GENERATED by scripts/film-data.mjs from the film's chapters.json — do not edit by hand.

export interface FilmSentence {
  text: string;
  start: number;
}

export interface FilmChapter {
  id: string;
  title: string;
  start: number;
  sentences: FilmSentence[];
}

export const FILM = {
  duration: ${Math.round(duration * 100) / 100},
  src: '/video/dmc-safety-how-it-works.mp4',
  poster: '/video/poster.jpg',
  captions: '/video/captions.vtt',
  chapters: ${JSON.stringify(chapters, null, 2).replace(/\n/g, '\n  ')} as FilmChapter[],
};
`;
writeFileSync(join(ROOT, 'src', 'film', 'filmData.ts'), ts);
writeFileSync(
  join(ROOT, 'src', 'film', 'filmMeta.ts'),
  `// GENERATED by scripts/film-data.mjs — just the film length, so pages that only
// link to the film don't bundle its transcript. 0 = no film yet.
export const FILM_DURATION = ${Math.round(duration * 100) / 100};
`,
);

// 3. how-it-works.html: video meta + VideoObject with one Clip per chapter
const iso = (s) => {
  const t = Math.round(s);
  const m = Math.floor(t / 60);
  return `PT${m ? `${m}M` : ''}${t % 60}S`;
};
const ld = {
  '@context': 'https://schema.org',
  '@type': 'VideoObject',
  name: 'How the Safety Dashboard works',
  description:
    'A self-regulated safety dashboard for Downtown Memphis: how businesses report what they see, how the Downtown public-safety team responds, and how the block stays in the loop.',
  thumbnailUrl: [`${SITE}/video/poster.jpg`, `${SITE}/video/og-image.png`],
  uploadDate,
  duration: iso(duration),
  contentUrl: `${SITE}/video/dmc-safety-how-it-works.mp4`,
  embedUrl: PAGE,
  inLanguage: 'en',
  publisher: { '@type': 'Organization', name: 'Core Downtown Memphis Safety Dashboard', url: SITE },
  hasPart: chapters.map((c, i) => ({
    '@type': 'Clip',
    name: c.title,
    startOffset: Math.floor(c.start),
    endOffset: Math.floor(i + 1 < chapters.length ? chapters[i + 1].start : duration),
    url: `${PAGE}?t=${Math.floor(c.start)}`,
  })),
};
const htmlPath = join(ROOT, 'how-it-works.html');
let html = readFileSync(htmlPath, 'utf8');
const fill = (name, body) => {
  const re = new RegExp(`(<!-- film:${name}:start -->)[\\s\\S]*?(\\s*<!-- film:${name}:end -->)`);
  if (!re.test(html)) throw new Error(`how-it-works.html: markers film:${name} not found`);
  html = html.replace(re, (_, a, b) => `${a}\n${body}${b}`);
};
fill('meta', `    <meta property="video:duration" content="${Math.round(duration)}" />`);
fill('jsonld', `    <script type="application/ld+json">${JSON.stringify(ld).replace(/</g, '\\u003c')}</script>`);
writeFileSync(htmlPath, html);

const mb = (statSync(join(out, 'dmc-safety-how-it-works.mp4')).size / 1048576).toFixed(1);
console.log(`film: ${chapters.length} chapters, ${words.length - chapters.length} sentences, ${iso(duration)}, video ${mb} MB`);
